
{
    "train_batch_size": 2,
        "gradient_accumulation_steps": 1,
            "zero_optimization": {
                  "stage": 2,
                        "offload_optimizer": {
                                "device": "cpu"
                                      }
                                        },
                                          "pipeline_parallel": {
                                                "enabled": true,
                                                      "stages": 2,
                                                            "activation_checkpointing": true
                                                                }
                                                            }

