#! /bin/bash
#SBATCH --job-name=333t_job # Job name
#SBATCH --output=/l/users/siem.hadish/3GPU0602.txt # Standard output and error.
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=40G
#SBATCH --cpus-per-task=64
#SBATCH --gres=gpu:3
#SBATCH -p cscc-gpu-p
#SBATCH --time=12:00:00
#SBATCH -q cscc-gpu-qos

nvidia-smi
chmod +x completeScriptP3GPU
pip install tqdm numpy matplotlib pandas scikit-learn
./completeScriptP
#./completeScriptP3GPU 
