#! /bin/bash
#SBATCH --job-name=justNVIDIA333t_job # Job name
#SBATCH --output=/l/users/siem.hadish/JustNvidia2GPU0402.txt # Standard output and error.
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=40G
#SBATCH --cpus-per-task=64
#SBATCH --gres=gpu:2
#SBATCH -p cscc-gpu-p
#SBATCH --time=12:00:00
#SBATCH -q cscc-gpu-qos

nvidia-smi
chmod +x completeScriptP3GPU
#pip install tqdm numpy matplotlib pandas scikit-learn
nvidia-smi > nvidia.txt
echo $CUDA_VISIBLE_DEVICES > cudiex.txt
#export CUDA_VISIBLE_DEVICES=0,1
nvidia-smi > nvidia2.txt
./completeScriptP
#./completeScriptP3GPU 
